[package]
name    = "dotenv-spec"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]
edition = "2018"

[dependencies]
serde_json = "1"
structopt  = "0.3"
pretty_env_logger = "0.3.1"
log = "0.4.8"
